#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

// #include "log.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	rt_entry_t * p = NULL;
	rt_entry_t * entry = NULL;

	list_for_each_entry(p, &rtable, list) {
		if ((p->dest & p->mask) == (dst & p->mask)) {
			if (entry == NULL) {
				entry = p;	
			} 
			else if (entry->mask < p->mask) {
				entry = p;
			}
		}
	}
	return entry;
}

// determine the next hop for the destination IP address
u32 get_next_hop(rt_entry_t* entry, u32 dst)
{
	if (entry->gw)
		return entry->gw;
	else
		return dst;
}

// forward the IP packet from the interface specified by longest_prefix_match, 
// when forwarding the packet, you should check the TTL, update the checksum,
// determine the next hop to forward the packet, then send the packet by 
// iface_send_packet_by_arp
void ip_forward_packet(u32 ip_dst, char* packet, int len)
{
	struct iphdr* hdr = packet_to_ip_hdr(packet);
	if (hdr->ttl <= 1) {
		icmp_send_packet(packet, len, ICMP_TIME_EXCEEDED, ICMP_EXC_TTL);
		free(packet);
		return;
	}

	hdr->ttl -= 1;
	hdr->checksum = ip_checksum(hdr);
	rt_entry_t* entry = longest_prefix_match(ip_dst);
	if (!entry) {
		icmp_send_packet(packet, len, ICMP_DEST_UNREACH, ICMP_NET_UNREACH);
		free(packet);
		return;
	}

	u32 next_hop = get_next_hop(entry, ip_dst);

	iface_info_t* iface = entry->iface;

	iface_send_packet_by_arp(iface, next_hop, packet, len);
}

// send IP packet
//
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	struct iphdr *head = packet_to_ip_hdr(packet);
	u32 dst = ntohl(head->daddr);
	rt_entry_t * entry = longest_prefix_match(dst);

	if (entry == NULL) {
		free(packet);
		return ;
	}

	u32 next_hop = entry->gw;
	if (!next_hop) {
		next_hop = dst;
	}

	struct ether_header *eh = (struct ether_header *)packet;
	eh->ether_type = ntohs(ETH_P_IP);
	memcpy(eh->ether_shost, entry->iface->mac, ETH_ALEN);

	iface_send_packet_by_arp(entry->iface, next_hop, packet, len);
}
